#ifndef YK_ALLOY_DETAIL_NO_UNIQUE_ADDRESS_HPP
#define YK_ALLOY_DETAIL_NO_UNIQUE_ADDRESS_HPP

#define YK_ALLOY_DETAIL_NO_UNIQUE_ADDRESS [[no_unique_address]]

#endif  // YK_ALLOY_DETAIL_NO_UNIQUE_ADDRESS_HPP
